# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160514_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodsuggestions',
            name='apk_version',
            field=models.IntegerField(null=True),
        ),
    ]
