# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160514_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFoodSuggestions',
            new_name='UserRecipeSuggestions',
        ),
    ]
